services:
  - type: web
    name: system-monitor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 5000
    healthCheckPath: /health 